Update & Accept suggestion
RealManClub/DCC_FE pull request #19
Opened 2023-04-06 15:11 UTC by kakao3450

* 피그마에 올라온 프로토타입 형태로 UI를 수정하였습니다.
* 앱, 웹, 응용 카테고리와 검색 버튼을 호버하였을 때 색깔이 바뀌게 설정하였습니다.
* 검색창에 Placeholer 추가, 클릭 시 사라지게 설정

2023-04-07 04:34 UTC, HarenKei requested changes
수정사항 변경해오세요.

2023-04-07 04:34 UTC, HarenKei commented on pages/NoticePost/NoticeBodyContainer.tsx
> +        <NoticeCard/>
이 부분은 추후에 리스트 렌더링을 공부해서 코드 한 줄로 여러 개의 컴포넌트를 렌더링 할 수 있도록 해보아요
JavaScript의 map 함수로 구현할 수 있어요

2023-04-07 04:34 UTC, HarenKei commented on pages/NoticePost/NoticeBodyContainer.tsx
> -  height: 15rem;
rem 단위는 최상위 HTML 문서의 크기 대비 상대 크기를 보여주므로 CSS 단위 중 ViewPort 단위를 공부하셔서 추후에 vw, vh 단위로 수정해주시면 감사하겠습니다. 지금은 일단 이 부분으로는 체인지 리퀘스트 걸지는 않을게요

2023-04-07 04:34 UTC, HarenKei commented on pages/NoticePost/NoticeBodyContainer.tsx
> -  box-shadow: 0 1px 8px rgba(0, 0, 0, 0.25);
box-shadow는 0px 1px 1px black으로 통일하겠읍니다.

2023-04-07 04:34 UTC, HarenKei commented on pages/NoticePost/NoticeMajor.tsx
>      <div>
최상위 div도 Styled-Component로 만든 컴포넌트로 구성해주시면 좋을 것 같아요.
제 작업 파일을 확인하시면 어떤 느낌일지 아실 것 같아요

2023-04-07 04:34 UTC, HarenKei commented on pages/NoticePost/NoticePost.tsx
>  const NoticeHeadContainer = styled.div`
컨테이너 하위의 아이템들의 위치를 잡을 때에는 margin보다는 flex 속성을 최대한 활용해주세요.

2023-04-07 04:34 UTC, HarenKei commented on pages/NoticePost/NoticePost.tsx
>  const Noticetitle = styled.div`
이 부분은 styled.div가 아니라 styled.h1, styled.h2 같이 직접 구성해주시면 감사하겠습니다. 쓸데없는 컴포넌트 사요을 줄일 수 있어요

2023-04-07 04:34 UTC, HarenKei commented on src/Common/NoticeCard.tsx
> +          <Img></Img>
Next.js에서는 img태그를 지양하고 next/Image를 사용하도록 유도하고 있습니다. Next.js의 Image 컴포넌트에는 src, width, height props가 무조건 들어가야 합니다.

2023-04-07 04:34 UTC, HarenKei commented on src/Common/NoticeCard.tsx
> +const Img = styled.div`
어허....어허... Img를 styled-component로 정의하지 말고 Next에서 제공하는 Image 컴포넌트를 Import해서 사용합시다.

2023-04-07 05:02 UTC, Charizard6 reviewed
참 잘 했어요

2023-04-10 02:17 UTC, Charizard6 reviewed
참 잘했어요.

2023-04-10 11:40 UTC, merged